# https://taskfile.dev

version: "3"

tasks:
  # multi-zippers
  all:
    desc: run example
    deps: [build]
    cmds:
      - task: run

  run:
    desc: run example
    deps: [zipper-2, sfn, zipper-1, source]

  build:
    run: once
    desc: go build
    cmds:
      - rm -rf bin
      - mkdir -p bin
      - go build -o bin/source source/source.go
      - go build -o bin/zipper-2 zipper-2/zipper_2.go
      - go build -o bin/zipper-1 zipper-1/zipper_1.go
      - go build -o bin/sfn sfn/sfn_echo.go
      - task: copy

  copy:
    desc: copy workflow configs
    cmds:
      - cp zipper-1/*.yaml bin/.
      - cp zipper-2/*.yaml bin/.

  zipper-2:
    desc: start services
    dir: bin
    env:
      YOMO_ENABLE_DEBUG: false
      YOMO_LOG_LEVEL: debug
    cmds:
      - ./zipper-2

  zipper-1:
    desc: start services
    dir: bin
    env:
      YOMO_ENABLE_DEBUG: false
      YOMO_LOG_LEVEL: debug
    cmds:
      - ./zipper-1

  sfn:
    desc: start services
    dir: bin
    env:
      YOMO_ENABLE_DEBUG: false
      YOMO_LOG_LEVEL: debug
    cmds:
      - ./sfn

  source:
    desc: run source
    dir: bin
    env:
      YOMO_ENABLE_DEBUG: false
      YOMO_LOG_LEVEL: debug
    cmds:
      - ./source
