# https://taskfile.dev

version: "3"

includes:
  example: ./example.yml
  cli: ./cli/cli.yml
  # multi-zipper: ./example/multi-zipper

tasks:
  default:
    cmds:
      - task -l
    silent: true
  multi_zipper:
    dir: example/multi-zipper
    desc: multi zipper example
    cmds:
      - task all
