# https://taskfile.dev

version: "3"

output: 'prefixed'

includes:
  example: 
    dir: ./example
    taskfile: ./example/Taskfile.yml
  cli: 
    dir: ./cli
    taskfile: ./cli/Taskfile.yml

tasks:
  default:
    cmds:
      - task -l
    silent: true
